services:
  postgres:
    image: postgres:16
    container_name: starcraft_postgres
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432" 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  starcraft-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starcraft_app
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge