// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarcraftOrganizer.Data.DataContext;

#nullable disable

namespace StarcraftOrganizer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250415182626_ChallengeMapsAdded")]
    partial class ChallengeMapsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player1VetoMapId")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player2VetoMapId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesFormat")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player1VetoMapId");

                    b.HasIndex("Player2Id");

                    b.HasIndex("Player2VetoMapId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.ChallengeMaps", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.HasKey("ChallengeId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("ChallengeMaps");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Map", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<bool>("Player1Won")
                        .HasColumnType("bit");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("MapId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Race")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Challenge", b =>
                {
                    b.HasOne("StarcraftOrganizer.Data.Entities.Player", "Player1")
                        .WithMany("ChallengesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Map", "Player1VetoMap")
                        .WithMany()
                        .HasForeignKey("Player1VetoMapId");

                    b.HasOne("StarcraftOrganizer.Data.Entities.Player", "Player2")
                        .WithMany("ChallengesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Map", "Player2VetoMap")
                        .WithMany()
                        .HasForeignKey("Player2VetoMapId");

                    b.Navigation("Player1");

                    b.Navigation("Player1VetoMap");

                    b.Navigation("Player2");

                    b.Navigation("Player2VetoMap");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.ChallengeMaps", b =>
                {
                    b.HasOne("StarcraftOrganizer.Data.Entities.Challenge", "Challenge")
                        .WithMany("ChallengeMaps")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Map", "Map")
                        .WithMany("ChallengeMaps")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Match", b =>
                {
                    b.HasOne("StarcraftOrganizer.Data.Entities.Challenge", "Challenge")
                        .WithMany("Matches")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarcraftOrganizer.Data.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Map");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Challenge", b =>
                {
                    b.Navigation("ChallengeMaps");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Map", b =>
                {
                    b.Navigation("ChallengeMaps");
                });

            modelBuilder.Entity("StarcraftOrganizer.Data.Entities.Player", b =>
                {
                    b.Navigation("ChallengesAsPlayer1");

                    b.Navigation("ChallengesAsPlayer2");
                });
#pragma warning restore 612, 618
        }
    }
}
